const url = {
    BASE_URL: "https://localhost:7218/api",
    MENU: {
        LIST: "/Menu",
    },
    AUTH: {
        PROFILE: "/Auth/staff/profile",
        LOGIN: "/Auth/staff-login",
        UPDATE_PROFILE: "/Auth/staff/update-profile",
        CHANGE_PASSWORD: "/Auth/staff/change-password",
        FORGOT_PASSWORD: "/Auth/staff/forgot-password",
        RESET_PASSWORD: "/Auth/Staff/reset-password",
    },
    CLASS: {
        LIST: "/classes",
        CLASSOFTEACHER: "/classes/get-by-teacher",
        CREATE: "/classes",
        EDIT: "/classes",
        DELETE: "/classes",
        DETAIL: "/classes/get-by-slug",
    },
    STUDENT: {
        LIST: "/student",
        CREATE: "/student",
        EDIT: "/student",
        DELETE: "/student",
        DELETE_FOREVER: "/student/permanently-delete",
        DETAIL: "/student/get-by-codeStudent",
        CLASS_ID: "/student/get-by-classId",
        TEST_SLUG: "/student/student-test/{}",
    },
    COURSE: {
        LIST: "/course",
        CREATE: "/course",
        DETAIL: "/product/get-by-codeCourse",
    },
    ClassCourse: {
        LIST: "/ClassCourse",
        CREATE: "/ClassCourse",
    },
    STAFF: {
        LIST: "/staff",
        CREATE: "/staff",
        DELETE: "/staff",
    },
    EXAM: {
        LIST: "/exam",
        CREATE: "/exam",
        EDIT: "/exam",
        DELETE: "/exam",
        DETAIL: "/exam/get-by-slug",
    },
    TEST: {
        LIST: "/test",
        TESTOFTEACHER: "/test/get-by-teacher",
        CREATE_MULTIPLE: "/test/multiple-choice-by-hand",
        CREATE_MULTIPLE_RETAKE: "/test/multiple-choice-by-hand/retake",
        CREATE_MULTIPLE_EXCEL: "/test/multiple-choice-by-excel-file",
        CREATE_MULTIPLE_EXCEL_RETAKE: "/test/multiple-choice-by-excel-file/retake",
        CREATE_MULTIPLE_AUTO: "/test/multiple-choice-by-auto",
        CREATE_MULTIPLE_AUTO_RETAKE: "/test/multiple-choice-by-auto/retake",
        CREATE_ESSAY: "/test/essay-by-hand",
        CREATE_ESSAY_RETAKE: "/test/essay-by-hand/retake",
        CREATE_ESSAY_AUTO: "/test/essay-by-auto",
        CREATE_ESSAY_AUTO_RETAKE: "/test/essay-by-auto/retake",
        EDIT: "/test",
        DELETE: "/test",
        DETAIL: "/test/get-by-slug",
        EXAM_ID: "/test/get-by-examId",
    },
    TESTQUESTION: {
        LIST: "/TestQuestion/{}",
        RESULT: "/TestQuestion/result-test/{}/details/{}",
    },
    GRADE: {
        LIST: "/grade",
    },
    ANSWER: {
        QUESTION_ID: "/answer/get-by-questionId",
        ANSWERFORSTUDENT: "/answersForStudent",
        SCORING: "/answersForStudent/scoring-essay",
    },
    RETEST: {
        LIST: "RegisterExam",
        CONFIRM: "RegisterExam/approve-register",
    },
    LOCKTEST: {
        LOCK: "/test/lock-test/{}",
        UNLOCK: "test/unlock-test/{}",
    },
};
export default url;
